# 7.- Arreglos con NUMPY

En este capítulo aprenderás a utilizar algunas cualidades básicas de NumPy (Numerical Python).
NumPy es una de las librerías más populares de Python, ya que puede procesar listas de múltiples
dimensiones

## 7.2.- Arreglo de Datos

Como en la sección anterior, invocaremos a la librería NumPy como np

In [1]:
pip install numpy

Armemos un arreglo de todos los factoriales del 1 al 6

In [2]:
import numpy as np
import math

# Crear un arreglo con los factoriales del 1 al 6
factoriales = np.array([math.factorial(i) for i in range(1, 7)])

# Mostrar el arreglo
print("Arreglo de factoriales del 1 al 6:", factoriales)


Arreglo de factoriales del 1 al 6: [  1   2   6  24 120 720]


Verifica el tipo de objeto que generamos

In [3]:
# Verificar el tipo de objeto
print("Tipo de objeto:", type(factoriales))

Tipo de objeto: <class 'numpy.ndarray'>


La función array copia automáticamente las dimensiones del argumento. Por ejemplo, el siguiente arreglo (array) está formado por tres filas y dos columnas.

In [4]:
# Crear un arreglo de 3 filas y 2 columnas
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])

# Mostrar el arreglo
print("Arreglo de 3x2:")
print(arr_2d)

# Verificar el tipo
print("Tipo de objeto:", type(arr_2d))


Arreglo de 3x2:
[[1 2]
 [3 4]
 [5 6]]
Tipo de objeto: <class 'numpy.ndarray'>


#### Por tu cuenta

Arma un arreglo de una dimensión desde una compresnidón de lista que produce todos los números nones del 1 al 30

In [5]:
# Crear un arreglo de números nones del 1 al 30
nones = np.array([x for x in range(1, 31) if x % 2 != 0])

# Mostrar el arreglo
print("Arreglo de números nones del 1 al 30:", nones)


Arreglo de números nones del 1 al 30: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]


### 7.2.2 - Atributos de Arreglos

En esta sección usaremos los siguientes 2 arreglos

enteros = np.array([[9,10,11,12],[8,7,6,5]])

flotantes=np.array([[9**(1/2),10**(1/2),3.33,],[10/3,3.4,3.03]])

In [6]:
import numpy as np

# Crear el arreglo de enteros
enteros = np.array([[9, 10, 11, 12], [8, 7, 6, 5]])

# Crear el arreglo de flotantes
flotantes = np.array([[9.5, 10.5, 3.33], [10/3, 3.4, 3.03]])

# Mostrar los arreglos
print("Arreglo de enteros:")
print(enteros)
print("\nArreglo de flotantes:")
print(flotantes)


Arreglo de enteros:
[[ 9 10 11 12]
 [ 8  7  6  5]]

Arreglo de flotantes:
[[ 9.5        10.5         3.33      ]
 [ 3.33333333  3.4         3.03      ]]


Checa el tipo de elemento con dtype

In [7]:
# Checar el tipo de datos de los arreglos
print("Tipo de datos (enteros):", enteros.dtype)
print("Tipo de datos (flotantes):", flotantes.dtype)


Tipo de datos (enteros): int64
Tipo de datos (flotantes): float64


Revisa que puedes ver dimensione con ndim y forma con shape del arreglo

In [8]:
# Checar las dimensiones y la forma de los arreglos
print("Dimensiones (enteros):", enteros.ndim)
print("Forma (enteros):", enteros.shape)

print("Dimensiones (flotantes):", flotantes.ndim)
print("Forma (flotantes):", flotantes.shape)

Dimensiones (enteros): 2
Forma (enteros): (2, 4)
Dimensiones (flotantes): 2
Forma (flotantes): (2, 3)


Size y itemsize te permite conocer el numero de elemntos y de bytes para almacenar

In [9]:
# Checar el número de elementos y el tamaño de cada elemento en bytes
print("Tamaño (enteros):", enteros.size)
print("Tamaño de cada elemento (enteros) en bytes:", enteros.itemsize)

print("Tamaño (flotantes):", flotantes.size)
print("Tamaño de cada elemento (flotantes) en bytes:", flotantes.itemsize)

Tamaño (enteros): 8
Tamaño de cada elemento (enteros) en bytes: 8
Tamaño (flotantes): 6
Tamaño de cada elemento (flotantes) en bytes: 8


Se puede iterar facilmente a través de un arreglo

In [10]:
# Iterar sobre los elementos de un arreglo
print("\nIterando sobre el arreglo de enteros:")
for fila in enteros:
    for num in fila:
        print(num, end=" ")
    print()  # Para salto de línea

print("\nIterando sobre el arreglo de flotantes:")
for fila in flotantes:
    for num in fila:
        print(num, end=" ")
    print()  # Para salto de línea



Iterando sobre el arreglo de enteros:
9 10 11 12 
8 7 6 5 

Iterando sobre el arreglo de flotantes:
9.5 10.5 3.33 
3.3333333333333335 3.4 3.03 


#### Por tu cuenta

Para el arreglo que armaste en el "Por tu cuenta" previo, checa el numero de dmiensiones y forma del arreglo

In [11]:
# Crear el arreglo de números nones del 1 al 30
nones = np.array([x for x in range(1, 31) if x % 2 != 0])

# Revisar dimensiones y forma
print("Dimensiones (nones):", nones.ndim)
print("Forma (nones):", nones.shape)


Dimensiones (nones): 1
Forma (nones): (15,)


### 7.2.3 - Creando Arreglos desde Rangos

La función arange (una sola R!!!!) nos permite crear rangos de enteros. Crea:

- Un arreglo del 0 al 7
- Un arreglo del 3 al 7
- Un arreglo del 12 al 2 en pasos de 3 en 3 (si, en orden inverso)

In [15]:
import numpy as np

arreglo_0_7 = np.arange(0, 8)
print("Arreglo del 0 al 7:", arreglo_0_7)


Arreglo del 0 al 7: [0 1 2 3 4 5 6 7]


In [14]:
arreglo_3_7 = np.arange(3, 8)
print("Arreglo del 3 al 7:", arreglo_3_7)


Arreglo del 3 al 7: [3 4 5 6 7]


In [17]:
arreglo_12_2 = np.arange(12, 1, -3)
print("Arreglo del 12 al 2 en pasos de 3:", arreglo_12_2)


Arreglo del 12 al 2 en pasos de 3: [12  9  6  3]


Tambien se pueden usar tamaños de paso no enteros. Crea un arreglo con linspace de 0 al 1 que vaya de .25 en .25

In [18]:
arreglo_linspace = np.linspace(0, 1, 5)
print("Arreglo con linspace de 0 a 1 en pasos de 0.25:", arreglo_linspace)


Arreglo con linspace de 0 a 1 en pasos de 0.25: [0.   0.25 0.5  0.75 1.  ]


In [21]:
# Crear un arreglo del 21 al 1 en orden inverso
arreglo_inverso = np.arange(21, 0, -1)

# Cambiar la forma a 4x5
matriz_4x5 = arreglo_inverso.reshape(4, 5)
print("Matriz 4x5:\n", matriz_4x5)

ValueError: cannot reshape array of size 21 into shape (4,5)

Checate que si el arreglo tiene 1000 o más elementos, numpy no muestra la totalidad de los datos. Generaun arreglo de 0 a 9999 y dale forma de 5 x 2000

In [22]:
import numpy as np

# Crear un arreglo de 0 a 9999
arr = np.arange(10000)

# Cambiarle la forma a 5x2000
arr_reshaped = arr.reshape(5, 2000)

# Imprimir el arreglo para ver cómo NumPy lo maneja
print(arr_reshaped)


[[   0    1    2 ... 1997 1998 1999]
 [2000 2001 2002 ... 3997 3998 3999]
 [4000 4001 4002 ... 5997 5998 5999]
 [6000 6001 6002 ... 7997 7998 7999]
 [8000 8001 8002 ... 9997 9998 9999]]


#### Por tu cuenta

Usa la función arange para crear una rreglo de 20 enteros pares del 42 al 80, y luego rearmalo en una matriz de 4x5

In [23]:
import numpy as np

# Crear un arreglo de enteros pares entre 42 y 80
arr = np.arange(42, 81, 2)

# Cambiarle la forma a 4x5
arr_reshaped = arr.reshape(4, 5)

print(arr_reshaped)


[[42 44 46 48 50]
 [52 54 56 58 60]
 [62 64 66 68 70]
 [72 74 76 78 80]]


### 7.2.4 - ¿Que tan más rapido es un arreglo?

Usa la magia %timeit y la librería random para crear una comprensión de lista que simule un tiro de dao 6000000 de veces y medir su tiempo

In [24]:
import random

# Usando comprensión de lista para simular el tiro de dado
%timeit [random.randint(1, 6) for _ in range(6000000)]

3.16 s ± 301 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Ahora usa %timeit para medir el tiempo de un tiro de dado 6000000 de veces pero hecho con arreglo

In [25]:
import numpy as np

# Usando un arreglo de NumPy para simular el tiro de dado
%timeit np.random.randint(1, 7, size=6000000)

81.7 ms ± 6.22 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### Por tu cuenta

Usa %timeit para ver que es mas rapido - una lista que sume todos los enteros del 0 al 9 999 999 o un arreglo que haga lo mismo con el metodo sum

In [26]:
# Usando lista para sumar los enteros del 0 al 9999999
%timeit sum([i for i in range(10000000)])

2.41 s ± 465 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [27]:
# Usando arreglo de NumPy para sumar los enteros del 0 al 9999999
%timeit np.sum(np.arange(10000000))


47.8 ms ± 1.33 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## 7.3.- Operaciones con Arreglos

Arma un arreglo de todos los pares del 2 al 15.

- Sumale 1 al arreglo
- Multiplicalo por 3
- Sacale raiz cuadrada

In [28]:
import numpy as np

# Arreglo de todos los pares entre 2 y 15
arr = np.arange(2, 16, 2)
print("Arreglo de pares:", arr)


Arreglo de pares: [ 2  4  6  8 10 12 14]


In [29]:
arr += 1
print("Arreglo después de sumar 1:", arr)


Arreglo después de sumar 1: [ 3  5  7  9 11 13 15]


In [30]:
arr *= 3
print("Arreglo después de multiplicar por 3:", arr)


Arreglo después de multiplicar por 3: [ 9 15 21 27 33 39 45]


In [31]:
arr = np.sqrt(arr)
print("Arreglo después de sacar la raíz cuadrada:", arr)


Arreglo después de sacar la raíz cuadrada: [3.         3.87298335 4.58257569 5.19615242 5.74456265 6.244998
 6.70820393]


Al mismo arreglo, aplicale un +=10

In [32]:
arr += 10
print("Arreglo después de sumarle 10:", arr)


Arreglo después de sumarle 10: [13.         13.87298335 14.58257569 15.19615242 15.74456265 16.244998
 16.70820393]


Arma un arreglo (lista1) que vaya del 2 al 18 de 3 en 3, y otro arreglo (lista2) usando linspace que vaya del -2 al 20 dividido en 6 numeros

- Resta lista1 de lista2
- divide lista2 entre lista1

In [33]:
# Arreglo lista1 del 2 al 18 con pasos de 3
lista1 = np.arange(2, 19, 3)

# Arreglo lista2 del -2 al 20 dividido en 6 números
lista2 = np.linspace(-2, 20, 6)

print("lista1:", lista1)
print("lista2:", lista2)


lista1: [ 2  5  8 11 14 17]
lista2: [-2.   2.4  6.8 11.2 15.6 20. ]


In [34]:
resta = lista2 - lista1
print("Resta de lista2 - lista1:", resta)

Resta de lista2 - lista1: [-4.  -2.6 -1.2  0.2  1.6  3. ]


In [35]:
division = lista2 / lista1
print("División de lista2 entre lista1:", division)

División de lista2 entre lista1: [-1.          0.48        0.85        1.01818182  1.11428571  1.17647059]


También puedes comparar los arreglos

In [36]:
comparacion = lista1 == lista2
print("Comparación de lista1 y lista2:", comparacion)

Comparación de lista1 y lista2: [False False False False False False]


#### Por tu cuenta

Crea un arreglo de los valores que vayan del 1 al 5, y luego elvealo al cuadrado usando **

In [37]:
# Crear arreglo del 1 al 5
arr1 = np.array([1, 2, 3, 4, 5])

# Elevar al cuadrado
arr1_squared = arr1 ** 2
print("Arreglo elevado al cuadrado:", arr1_squared)


Arreglo elevado al cuadrado: [ 1  4  9 16 25]


### 7.3.2.- Métodos de Cálculo

Considera el siguiente arreglo

ventas=np.array( [[554,606,710,851],[1244,898,416,1763],
 [841,655,1105,1067]])


In [38]:
import numpy as np

# Arreglo de ventas
ventas = np.array([[554, 606, 710, 851],
                   [1244, 898, 416, 1763],
                   [841, 655, 1105, 1067]])

print("Arreglo de ventas:")
print(ventas)


Arreglo de ventas:
[[ 554  606  710  851]
 [1244  898  416 1763]
 [ 841  655 1105 1067]]


Podemos usar métodos para calcular la sum, min, max, mean, std, var.

In [39]:
suma_total = ventas.sum()
print("Suma total de todas las ventas:", suma_total)

Suma total de todas las ventas: 10710


In [40]:
min_ventas = ventas.min()
print("Valor mínimo de ventas:", min_ventas)

Valor mínimo de ventas: 416


In [41]:
max_ventas = ventas.max()
print("Valor máximo de ventas:", max_ventas)

Valor máximo de ventas: 1763


In [42]:
mean_ventas = ventas.mean()
print("Media de las ventas:", mean_ventas)

Media de las ventas: 892.5


In [43]:
std_ventas = ventas.std()
print("Desviación estándar de las ventas:", std_ventas)

Desviación estándar de las ventas: 350.56656524355924


In [44]:
var_ventas = ventas.var()
print("Varianza de las ventas:", var_ventas)

Varianza de las ventas: 122896.91666666667


También es posible hacerlo por filas y columnas. Checa como se hace con axis = 1 y 0

In [45]:
# Sumar por columnas
suma_columnas = ventas.sum(axis=0)
print("Suma por columnas:", suma_columnas)

# Media por columnas
media_columnas = ventas.mean(axis=0)
print("Media por columnas:", media_columnas)

# Desviación estándar por columnas
std_columnas = ventas.std(axis=0)
print("Desviación estándar por columnas:", std_columnas)

# Varianza por columnas
var_columnas = ventas.var(axis=0)
print("Varianza por columnas:", var_columnas)


Suma por columnas: [2639 2159 2231 3681]
Media por columnas: [ 879.66666667  719.66666667  743.66666667 1227.        ]
Desviación estándar por columnas: [283.01511542 127.67754523 282.28866235 389.13236822]
Varianza por columnas: [ 80097.55555556  16301.55555556  79686.88888889 151424.        ]


In [46]:
# Sumar por filas
suma_filas = ventas.sum(axis=1)
print("Suma por filas:", suma_filas)

# Media por filas
media_filas = ventas.mean(axis=1)
print("Media por filas:", media_filas)

# Desviación estándar por filas
std_filas = ventas.std(axis=1)
print("Desviación estándar por filas:", std_filas)

# Varianza por filas
var_filas = ventas.var(axis=1)
print("Varianza por filas:", var_filas)


Suma por filas: [2721 4321 3668]
Media por filas: [ 680.25 1080.25  917.  ]
Desviación estándar por filas: [113.46007007 491.78367958 181.84058953]
Varianza por filas: [ 12873.1875 241851.1875  33066.    ]


#### Por tu cuenta

Usa el generador de numeros aleatoreos de numpy (np.random.randint) para crear una rreglo de 12 calificaciones aleatorias del 60 al 100, y luego dale forma en una matriz de 3x4. Calcula el promedio de todas las calificaciones, el promedio de cada columna y de cada fila.

In [47]:
calificaciones = np.random.randint(60, 101, size=12)

# Darle forma de 3x4
calificaciones_matrix = calificaciones.reshape(3, 4)

In [48]:
print("Matriz de calificaciones:")
print(calificaciones_matrix)

Matriz de calificaciones:
[[69 66 61 71]
 [61 62 61 83]
 [79 60 78 70]]


In [50]:
promedio_total = calificaciones_matrix.mean()
print("Promedio total de las calificaciones:", promedio_total)

Promedio total de las calificaciones: 68.41666666666667


In [51]:
# Promedio por columna
promedio_columnas = calificaciones_matrix.mean(axis=0)
print("Promedio por columna:", promedio_columnas)

Promedio por columna: [69.66666667 62.66666667 66.66666667 74.66666667]


In [52]:
# Promedio por fila
promedio_filas = calificaciones_matrix.mean(axis=1)
print("Promedio por fila:", promedio_filas)

Promedio por fila: [66.75 66.75 71.75]


## 7.4.- Indexando y Cortando arreglos

Crea el arreglo

ventas=np.array ([[ 554, 606, 710, 851],
 [1244, 898, 416, 1763],
 [ 841, 655, 1105, 1067]])

 - Selecciona el item 2,1
 - Selecciona el item 1,3
 - Selecciona la fila 1

In [53]:
import numpy as np

ventas = np.array([[554, 606, 710, 851],
                   [1244, 898, 416, 1763],
                   [841, 655, 1105, 1067]])

print("Arreglo de ventas:")
print(ventas)


Arreglo de ventas:
[[ 554  606  710  851]
 [1244  898  416 1763]
 [ 841  655 1105 1067]]


In [55]:
item_2_1 = ventas[2, 1]
print("Elemento en la posición (2,1):", item_2_1)


Elemento en la posición (2,1): 655


In [56]:
item_1_3 = ventas[1, 3]
print("Elemento en la posición (1,3):", item_1_3)


Elemento en la posición (1,3): 1763


In [57]:
fila_1 = ventas[1]
print("Fila 1:", fila_1)


Fila 1: [1244  898  416 1763]


Solicita las filas con índices 0 y 1

In [54]:
filas_0_1 = ventas[0:2]  # Selecciona las filas 0 y 1
print("Filas con índices 0 y 1:")
print(filas_0_1)


Filas con índices 0 y 1:
[[ 554  606  710  851]
 [1244  898  416 1763]]


Ahora para solicitar las filas con indices 1 y 2

In [58]:
filas_1_2 = ventas[1:3]  # Selecciona las filas 1 y 2
print("Filas con índices 1 y 2:")
print(filas_1_2)


Filas con índices 1 y 2:
[[1244  898  416 1763]
 [ 841  655 1105 1067]]


Quieres solo los elementos de la primera columna?

In [59]:
columna_1 = ventas[:, 0]
print("Primera columna:")
print(columna_1)


Primera columna:
[ 554 1244  841]


Que la las columnas con indices 0 y 2?

In [60]:
columnas_0_2 = ventas[:, [0, 2]]
print("Columnas con índices 0 y 2:")
print(columnas_0_2)

Columnas con índices 0 y 2:
[[ 554  710]
 [1244  416]
 [ 841 1105]]


#### Por tu cuenta

Dado el siguiente arreglo

array([[1,2,3,4,5],
     [6,7,8,9,10],
     [11,12,13,14,15]])

- Selecciona la segunda fila
- Selecciona la primera y tercera fila
- Selecciona las tres columnas de enmedio

In [61]:
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15]])

print("Arreglo:")
print(arr)



Arreglo:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [63]:
segunda_fila = arr[1]
print("Segunda fila:", segunda_fila)



Segunda fila: [ 6  7  8  9 10]


In [64]:
primer_y_tercer_fila = arr[[0, 2]]
print("Primera y tercera fila:")
print(primer_y_tercer_fila)


Primera y tercera fila:
[[ 1  2  3  4  5]
 [11 12 13 14 15]]


In [65]:
columnas_medio = arr[:, 1:4]
print("Las tres columnas del medio:")
print(columnas_medio)


Las tres columnas del medio:
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


### 7.4.2.- Transponer

Con **reshape** puedes producir una copia superficial del arreglo con una nueva dimension.

ventas = np.array([[ 500, 600, 550, 800],
 [1200, 800, 400,1000]])

Usa el arreglo anterior para darle dimension de 1x8

In [66]:
import numpy as np

ventas = np.array([[500, 600, 550, 800],
                   [1200, 800, 400, 1000]])

print("Arreglo de ventas:")
print(ventas)


Arreglo de ventas:
[[ 500  600  550  800]
 [1200  800  400 1000]]


In [68]:
ventas_reshaped = ventas.reshape(1, 8)
print("\nVentas después de reshape a 1x8:")
print(ventas_reshaped)



Ventas después de reshape a 1x8:
[[ 500  600  550  800 1200  800  400 1000]]


El metodo **resize** modifica la forma del original (no crea copia)

In [69]:
ventas.resize(1, 8)
print("\nVentas después de resize a 1x8 (modificando el original):")
print(ventas)



Ventas después de resize a 1x8 (modificando el original):
[[ 500  600  550  800 1200  800  400 1000]]


Y **transpose** rapidamente le da la vuelta a filas y columnas, este se hace aplicando el atributo T, que no modifica el original, solo una vista.

In [70]:
ventas_transposed = ventas.T
print("\nVentas después de transponer (filas y columnas intercambiadas):")
print(ventas_transposed)



Ventas después de transponer (filas y columnas intercambiadas):
[[ 500]
 [ 600]
 [ 550]
 [ 800]
 [1200]
 [ 800]
 [ 400]
 [1000]]


## 7.5.- Pandas - Series

Vamos a usar estos datos para Series - tiempo_web = pd.Series([160,256,98,108])

Este es el tiempo que invierten en videojuegos 4 estudiantes

In [71]:
import pandas as pd

# Crear la serie
tiempo_web = pd.Series([160, 256, 98, 108])

print("Serie tiempo_web:")
print(tiempo_web)


Serie tiempo_web:
0    160
1    256
2     98
3    108
dtype: int64


Para crear una serie con el mismo elemento

In [72]:
serie_unico = pd.Series([100] * 5)  # Crea una serie de 5 elementos con el valor 100
print("\nSerie con el mismo valor en todos los elementos:")
print(serie_unico)



Serie con el mismo valor en todos los elementos:
0    100
1    100
2    100
3    100
4    100
dtype: int64


Acceder a un elemento es facil

In [73]:
primer_elemento = tiempo_web[0]
print("\nPrimer elemento de tiempo_web:", primer_elemento)



Primer elemento de tiempo_web: 160


Series tiene acceso a los mismos metodos que arreglos para estadistica descriptiva

In [74]:
# Estadísticas básicas de la serie
min_value = tiempo_web.min()
max_value = tiempo_web.max()
mean_value = tiempo_web.mean()

print("\nMínimo:", min_value)
print("Máximo:", max_value)
print("Promedio:", mean_value)


Mínimo: 98
Máximo: 256
Promedio: 155.5


Tambien, todo esto se puede resumir con **describe**

In [75]:
# Estadísticas descriptivas completas
descripcion = tiempo_web.describe()
print("\nEstadísticas descriptivas completas:")
print(descripcion)



Estadísticas descriptivas completas:
count      4.000000
mean     155.500000
std       72.302605
min       98.000000
25%      105.500000
50%      134.000000
75%      184.000000
max      256.000000
dtype: float64


También podemos personalizar los indices de series a traves de index

['Laura','Daniel','Alberto','Eva']

Asigna esos nombres

In [76]:
# Nombres personalizados como índice
tiempo_web_personalizado = pd.Series([160, 256, 98, 108], index=['Laura', 'Daniel', 'Alberto', 'Eva'])
print("\nSerie con índices personalizados:")
print(tiempo_web_personalizado)



Serie con índices personalizados:
Laura      160
Daniel     256
Alberto     98
Eva        108
dtype: int64


O puedes usar un diccionario para eso:

In [77]:
# Usando un diccionario para crear la serie
tiempo_web_dict = pd.Series({
    'Laura': 160,
    'Daniel': 256,
    'Alberto': 98,
    'Eva': 108
})

print("\nSerie creada con diccionario:")
print(tiempo_web_dict)



Serie creada con diccionario:
Laura      160
Daniel     256
Alberto     98
Eva        108
dtype: int64


Puedes llamar a los elementos personalizados

In [78]:
# Acceder a los elementos por nombre
daniel_tiempo = tiempo_web_personalizado['Daniel']
print("\nTiempo de Daniel:", daniel_tiempo)



Tiempo de Daniel: 256


Tambien se pueden llamar como atributos

In [79]:
# Acceder como atributo
daniel_tiempo_attr = tiempo_web_personalizado.Daniel
print("\nAcceso como atributo (Daniel):", daniel_tiempo_attr)



Acceso como atributo (Daniel): 256


#### Por tu cuenta

Usa el generador aleatorio de NumPy (np.random.randint) para generar 6 calificaciones del 60 al 100 y guardarlos en una serie.

A continuación arma las siguientes tareas:

- Convierte el arreglo en una serie llamada calificacion
- Determina la min, max y promedio
- Produce TODAS las estadisticas descriptivas

In [80]:
import numpy as np

# Generar 6 calificaciones aleatorias entre 60 y 100
calificaciones = np.random.randint(60, 101, 6)

# Convertir el arreglo en una serie
calificacion = pd.Series(calificaciones)

print("\nSerie de calificaciones:")
print(calificacion)

# Obtener el mínimo, máximo y promedio
min_calif = calificacion.min()
max_calif = calificacion.max()
promedio_calif = calificacion.mean()

print("\nMínima calificación:", min_calif)
print("Máxima calificación:", max_calif)
print("Promedio de calificaciones:", promedio_calif)

# Estadísticas descriptivas completas
estadisticas_calif = calificacion.describe()
print("\nEstadísticas descriptivas de las calificaciones:")
print(estadisticas_calif)



Serie de calificaciones:
0    94
1    90
2    72
3    84
4    89
5    88
dtype: int64

Mínima calificación: 72
Máxima calificación: 94
Promedio de calificaciones: 86.16666666666667

Estadísticas descriptivas de las calificaciones:
count     6.000000
mean     86.166667
std       7.652886
min      72.000000
25%      85.000000
50%      88.500000
75%      89.750000
max      94.000000
dtype: float64


## 7.6.- Pandas - DataFrames

##### Crear un Dataframe de un diccionario

Agarra este diccionario y conviertelo en un dataframe

 reg_peso = {'Vanesa':[68,67,66,65],'Kevin':[89,89,90,88],
 'Fernanda':[59,60,60,62],'Patricia':[70,68,67,65]}

In [81]:
import pandas as pd

# Diccionario con los datos
reg_peso = {
    'Vanesa': [68, 67, 66, 65],
    'Kevin': [89, 89, 90, 88],
    'Fernanda': [59, 60, 60, 62],
    'Patricia': [70, 68, 67, 65]
}

In [82]:
# Convertir el diccionario en un DataFrame
peso = pd.DataFrame(reg_peso)

# Imprimir el DataFrame original
print("DataFrame original:")
print(peso)

DataFrame original:
   Vanesa  Kevin  Fernanda  Patricia
0      68     89        59        70
1      67     89        60        68
2      66     90        60        67
3      65     88        62        65


##### El atributo Index

Añade los siguientes indices personalizados

peso.index = ['Mes 1','Mes 2','Mes 3','Mes 4']

In [83]:
# Añadir los índices personalizados
peso.index = ['Mes 1', 'Mes 2', 'Mes 3', 'Mes 4']

print("\nDataFrame con índices personalizados:")
print(peso)



DataFrame con índices personalizados:
       Vanesa  Kevin  Fernanda  Patricia
Mes 1      68     89        59        70
Mes 2      67     89        60        68
Mes 3      66     90        60        67
Mes 4      65     88        62        65


##### Accesar Columnas

Selecciona la información de Fernanda

In [87]:
fernanda_info = peso['Fernanda']
print("\nInformación de Fernanda:")
print(fernanda_info)



Información de Fernanda:
Mes 1    59
Mes 2    60
Mes 3    60
Mes 4    62
Name: Fernanda, dtype: int64


Selecciona la de Patricia pero como atributo

In [86]:
patricia_info = peso.Patricia
print("\nInformación de Patricia (como atributo):")
print(patricia_info)



Información de Patricia (como atributo):
Mes 1    70
Mes 2    68
Mes 3    67
Mes 4    65
Name: Patricia, dtype: int64


##### Loc y iloc

Selecciona la información del Mes1 usando Loc

In [88]:
mes1_info = peso.loc['Mes 1']
print("\nInformación del Mes 1 (usando loc):")
print(mes1_info)



Información del Mes 1 (usando loc):
Vanesa      68
Kevin       89
Fernanda    59
Patricia    70
Name: Mes 1, dtype: int64


Ahora solo la fila 1 usando iloc

In [89]:
fila1_info = peso.iloc[0]
print("\nInformación de la fila 1 (usando iloc):")
print(fila1_info)



Información de la fila 1 (usando iloc):
Vanesa      68
Kevin       89
Fernanda    59
Patricia    70
Name: Mes 1, dtype: int64


Ahora del Mes 1 al Mes 3 usando loc

In [90]:
meses1_3_info = peso.loc['Mes 1':'Mes 3']
print("\nInformación de los Meses 1 a 3 (usando loc):")
print(meses1_3_info)


Información de los Meses 1 a 3 (usando loc):
       Vanesa  Kevin  Fernanda  Patricia
Mes 1      68     89        59        70
Mes 2      67     89        60        68
Mes 3      66     90        60        67


Saca filas especificas (mes 1 y 3) usando loc

In [91]:
meses_1_3 = peso.loc[['Mes 1', 'Mes 3']]
print("\nInformación de los Meses 1 y 3 (usando loc):")
print(meses_1_3)



Información de los Meses 1 y 3 (usando loc):
       Vanesa  Kevin  Fernanda  Patricia
Mes 1      68     89        59        70
Mes 3      66     90        60        67


Y ahora los Meses 2 y 3 de Vanesa y Patricia solamente con loc

In [92]:
vanesa_patricia_mes2_3 = peso.loc[['Mes 2', 'Mes 3'], ['Vanesa', 'Patricia']]
print("\nInformación de Vanesa y Patricia en los Meses 2 y 3 (usando loc):")
print(vanesa_patricia_mes2_3)



Información de Vanesa y Patricia en los Meses 2 y 3 (usando loc):
       Vanesa  Patricia
Mes 2      67        68
Mes 3      66        67


##### Indices Booleanos

Dime los pesos mayores a 70kg en la tabla

In [94]:
pesos_mayores_70 = peso[peso > 70]
print("\nPesos mayores a 70kg:")
print(pesos_mayores_70)



Pesos mayores a 70kg:
       Vanesa  Kevin  Fernanda  Patricia
Mes 1     NaN     89       NaN       NaN
Mes 2     NaN     89       NaN       NaN
Mes 3     NaN     90       NaN       NaN
Mes 4     NaN     88       NaN       NaN


Y ahora los pesos mayores a 65kg y menores a 80kg

In [95]:
pesos_rango_65_80 = peso[(peso > 65) & (peso < 80)]
print("\nPesos entre 65kg y 80kg:")
print(pesos_rango_65_80)



Pesos entre 65kg y 80kg:
       Vanesa  Kevin  Fernanda  Patricia
Mes 1    68.0    NaN       NaN      70.0
Mes 2    67.0    NaN       NaN      68.0
Mes 3    66.0    NaN       NaN      67.0
Mes 4     NaN    NaN       NaN       NaN


##### Accesar una celda especifica de un Dataframe

Que pasa si solo queremos cuanto pesaba Patricia en el mes 3? Usa at

In [96]:
# Acceder a la celda específica usando at
peso_patricia_mes3 = peso.at['Mes 3', 'Patricia']
print("\nPeso de Patricia en el Mes 3:", peso_patricia_mes3)



Peso de Patricia en el Mes 3: 67


Resulta que Kevin en realidad pesaba 85kg en el mes 4, cambia su valor usando at

In [97]:
# Cambiar el valor de Kevin en el Mes 4 usando at
peso.at['Mes 4', 'Kevin'] = 85
print("\nDataFrame con peso de Kevin actualizado en el Mes 4:")
print(peso)



DataFrame con peso de Kevin actualizado en el Mes 4:
       Vanesa  Kevin  Fernanda  Patricia
Mes 1      68     89        59        70
Mes 2      67     89        60        68
Mes 3      66     90        60        67
Mes 4      65     85        62        65


##### Estádistica descriptiva

Puedes usar el metodo **Describe** para sacar todas las estadisticas del dataframe

In [98]:
estadisticas = peso.describe()
print("\nEstadísticas descriptivas completas:")
print(estadisticas)



Estadísticas descriptivas completas:
          Vanesa      Kevin   Fernanda   Patricia
count   4.000000   4.000000   4.000000   4.000000
mean   66.500000  88.250000  60.250000  67.500000
std     1.290994   2.217356   1.258306   2.081666
min    65.000000  85.000000  59.000000  65.000000
25%    65.750000  88.000000  59.750000  66.500000
50%    66.500000  89.000000  60.000000  67.500000
75%    67.250000  89.250000  60.500000  68.500000
max    68.000000  90.000000  62.000000  70.000000


También puedes cambiar la cantidad de decimales usando **Precision**

In [106]:
# Cambiar la precisión a 2 decimales
peso = peso.round(2)
print("\nDataFrame con precisión de 2 decimales:")
print(peso)



DataFrame con precisión de 2 decimales:
       Vanesa  Kevin  Fernanda  Patricia
Mes 1      68     89        59        70
Mes 2      67     89        60        68
Mes 3      66     90        60        67
Mes 4      65     85        62        65


Y también se pueden aplicar los metodos de estadistica descriptiva individuales como mean

In [100]:
# Promedio de los pesos por persona
promedio_peso = peso.mean()
print("\nPromedio de los pesos por persona:")
print(promedio_peso)



Promedio de los pesos por persona:
Vanesa      66.50
Kevin       88.25
Fernanda    60.25
Patricia    67.50
dtype: float64


##### Transponer

Si quisieramos voltear el dataframe, tendríamos que hacer el método T

In [101]:
# Transponer el DataFrame
peso_transpuesto = peso.T
print("\nDataFrame transpuesto:")
print(peso_transpuesto)



DataFrame transpuesto:
          Mes 1  Mes 2  Mes 3  Mes 4
Vanesa       68     67     66     65
Kevin        89     89     90     85
Fernanda     59     60     60     62
Patricia     70     68     67     65


Y ahora eso nos ayudaría a sacar los estadísticos para los meses en vez de para las personas

Y el peso promedio por mes de nuestra gente

In [102]:
# Promedio de peso por mes
promedio_peso_mes = peso_transpuesto.mean()
print("\nPromedio de peso por mes:")
print(promedio_peso_mes)


Promedio de peso por mes:
Mes 1    71.50
Mes 2    71.00
Mes 3    70.75
Mes 4    69.25
dtype: float64


##### Ordenar el Dataframe

Ahora vamos a arreglar el dataframe por fila, con los indices en orden descendente

In [109]:
# Ordenar el DataFrame por índices en orden descendente
peso_ordenado_indices = peso.sort_index(ascending=False)
print("\nDataFrame ordenado por índices en orden descendente:")
print(peso_ordenado_indices)


DataFrame ordenado por índices en orden descendente:
       Vanesa  Kevin  Fernanda  Patricia
Mes 4      65     85        62        65
Mes 3      66     90        60        67
Mes 2      67     89        60        68
Mes 1      68     89        59        70


Las columnas en orden ascendente

In [110]:
# Ordenar las columnas en orden ascendente
peso_ordenado_columnas = peso.sort_index(axis=1)
print("\nDataFrame con columnas ordenadas en orden ascendente:")
print(peso_ordenado_columnas)



DataFrame con columnas ordenadas en orden ascendente:
       Fernanda  Kevin  Patricia  Vanesa
Mes 1        59     89        70      68
Mes 2        60     89        68      67
Mes 3        60     90        67      66
Mes 4        62     85        65      65


Y también se vale ordenar los valores según una fila o columna especifica.  El siguiente código ordena de forma descendente los datos del DataFrame con respecto
a los valores del Mes 1.

In [112]:
# Ordenar por la fila 'Mes 1' (descendente)
peso_ordenado_mes1 = peso.sort_values(by='Mes 1', axis=1, ascending=False)
print("\nDataFrame ordenado por los valores del Mes 1 (descendente):")
print(peso_ordenado_mes1)



DataFrame ordenado por los valores del Mes 1 (descendente):
       Kevin  Patricia  Vanesa  Fernanda
Mes 1     89        70      68        59
Mes 2     89        68      67        60
Mes 3     90        67      66        60
Mes 4     85        65      65        62
